# Generated by Django 5.1.1 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id_troca', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('año', models.PositiveIntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('tipo_llantas', models.CharField(max_length=50)),
            ],
        ),
    ]
